name: contacts_service
description: A Flutter plugin to retrieve and manage contacts on Android and iOS devices.
version: 0.6.3
homepage: https://github.com/lukasgit/flutter_contacts
maintainer: Lukas Dickie (@lukasgit)

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  collection:
  quiver:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  plugin:
    platforms:
      android:
        package: flutter.plugins.contactsservice.contacts_service
        pluginClass: ContactsServicePlugin
      ios:
        pluginClass: ContactsServicePlugin